### ISSUE TITLE
libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dharmeshkakadia** [kubeflow/kubeflow#414]
I am following the user guide (https://github.com/kubeflow/kubeflow/blob/master/user_guide.md) and got the following error. I am running k8s on azure with GPU instances. I am running master code. Is there an issue with the image?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/opt/conda/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

/opt/conda/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-b0e475b6b7de> in <module>()
----> 1 from tensorflow.examples.tutorials.mnist import input_data
      2 mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
      3 
      4 import tensorflow as tf
      5 

/opt/conda/lib/python3.6/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *  # pylint: disable=redefined-builtin
     25 # pylint: enable=wildcard-import
     26 

/opt/conda/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by dharmeshkakadia** [comment]
May be related to this : https://github.com/tensorflow/tensorflow/issues/15604 but I dont really understand how the gcr.io/kubeflow-images-staging/tensorflow-notebook-gpu image is built.

**Comment by wbuchwalter** [comment]
@dharmeshkakadia How did you create your kubernetes cluster on Azure? acs-engine or AKS?
did you set the `cloud` param to `azure` in ksonnet when deploying Kubeflow?

**Comment by dharmeshkakadia** [comment]
acs-engine. I didn't find really antything related to azure so I had KUBECONFIG pointing to the cluster and deployed without using env. Is that a problem?

**Comment by wbuchwalter** [comment]
You need to set `env` properly so that the operator mounts the NVIDIA driver for you into the pods (since Azure isn't yet using device plugin).
However the configuration provided for Azure is for AKS.
acs-engine driver's installation has been updated recently to make it easier so it uses different mount points (this will makes it's way to AKS soon).
You have two options:
1/ Either Create a new cluster with AKS instead, and set `env` to `azure` in ksonnet, this should work right away

2/ Or in your ksonnet app, modify `vendor/kubeflow/core/tf-job.libsonnet` so that:
```js

    azureAccelerators:: {
      accelerators: {
        "alpha.kubernetes.io/nvidia-gpu": {
          volumes: [
            {
              name: "lib",
              mountPath: "/usr/local/nvidia/lib64",
              hostPath: "/usr/lib/nvidia-384",
            },
            {
              name: "bin",
              mountPath: "/usr/local/nvidia/bin",
              hostPath: "/usr/lib/nvidia-384/bin",
            },
            {
              name: "libcuda",
              mountPath: "/usr/lib/x86_64-linux-gnu/libcuda.so.1",
              hostPath: "/usr/lib/x86_64-linux-gnu/libcuda.so.1",
            },
          ],
        },
      },
    },
```

becomes:
```js
    azureAccelerators:: {
      accelerators: {
        "alpha.kubernetes.io/nvidia-gpu": {
          volumes: [
            {
              name: "nvidia",
              mountPath: "/usr/local/nvidia",
              hostPath: "/usr/local/nvidia",
            }],
        },
      },
    },
```

Then redeploy the ksonnet app (don't forget to set `env` to `azure`).

I'll try to make a PR to make this easier :)

**Comment by dharmeshkakadia** [comment]
I tried the second approach but still see the same error. Here is what I did.
ks delete default -c kubeflow-core
vim vendor/kubeflow/core/tf-job.libsonnet
ks env add cloud
ks param set kubeflow-core cloud azure --env=cloud
KF_ENV=cloud
ks apply ${KF_ENV} -c kubeflow-core
ks apply default -c kubeflow-core

Did I miss anything?

**Comment by dharmeshkakadia** [comment]
!ls /usr/local/nvidia/ says No such file or directory

**Comment by dharmeshkakadia** [comment]
!ls /usr/local/ gives 
bin  cuda  cuda-8.0  etc  games  include  lib  man  sbin  share  src

**Comment by ernestmartinez** [comment]
I'm having the same problem trying to run any jobs in a jupyter notebook. From the jupyter terminal I did a search and found the installed libraries are:
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcublas.so.8.0.88
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcublas.so.8.0
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcublas.so.8.0.61

**Comment by yongwen** [comment]
i think the latest docker image gcr.io/kubeflow-images-staging/tensorflow-notebook-gpu is not build correctly. From the components/tensorflow-notebook-image/Makefile, it specify the cuda version 8.0, as in "nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04" and using the nightly TF build.  Since the nightly TF build had been moved to using cuda:9.0, thus the error.

I could send in a PR to fix the build issue.

in the mean time, here is an older gpu docker image version seems to work for me: gcr.io/kubeflow/tensorflow-notebook-gpu:8fbc341245695e482848ac3c2034a99f7c1e5763

**Comment by ernestmartinez** [comment]
Thanks I'll try it tomorrow.

**Comment by dharmeshkakadia** [comment]
I have more details, after I re-provisioned the cluster, I am not seeing the GPU on the node
....
Capacity:
alpha.kubernetes.io/nvidia-gpu:  0
...

I will appreciate if others have a pointer for debugging this.

**Comment by dharmeshkakadia** [comment]
Update: 
Re-provisioning using 0.14 acs-engine makes the node GPUs recognized, but kubeflow is failing with
"0/2 nodes are available: 1 PodToleratesNodeTaints, 2 Insufficient nvidia.com/gpu"

Note that node describe output has the GPUs now:
....
Capacity:
 alpha.kubernetes.io/nvidia-gpu:  4
....

**Comment by dharmeshkakadia** [comment]
Update:
"2 Insufficient nvidia.com/gpu" was because I was specifying "{"nvidia.com/gpu": "1"}" instead of "{"alpha.kubernetes.io/nvidia-gpu": "1"}"  while following the example, since the acs-engine is not using device plugin.

Specifying the correct resource limit, I am back the error at the start of this issue "ImportError: libcuda.so.1: cannot open shared object file: No such file or directory" 🤷‍♂️

**Comment by estelleaf** [comment]
Hi 
Here after is how I fixed it:

On my computer I had :

    cudnn5.1,   
    cuda8.0


When importing tensorflow, I had the same error ImportError: 

> libcublas.so.8.0: cannot open shared object file: No such file or
> directory

and even 

> libcublas.so.9.0: cannot open shared object file: No such file or
> directory


To overcome the second issue I installed `tensorflow 1.4` instead of 1.6 
 and for the first I did
$ export PATH="$PATH:/usr/local/cuda-8.0/bin" 
$ export LD_LIBRARY_PATH="/usr/local/cuda-8.0/lib64"


But then I had another issue : 

> libcudnn.so.6: cannot open shared object file: No such file or
> directory

This was because I had cudnn5.1 as required but actually it needs cudnn6

Here are the steps to uninstall cudnn5.1 and install cudnn6:

1- Uninstall cudnn 5.1
    rm -f /usr/include/cudnn.h
    rm -f /usr/lib/x86_64-linux-gnu/libcudnn
    rm -f /usr/local/cuda-/lib64/libcudnn

2- Install cudnn6

After having subscribed to nvdia, go to here https://developer.nvidia.com/rdp/cudnn-download and download cudnn6 for cuda8 and then go to the folder where you downloaded the cudnn and do :

    $ tar xvzf cudnn-8.0-linux-x64-v5.1-ga.tgz
    $ sudo cp -P cuda/include/cudnn.h /usr/local/cuda/include
    $ sudo cp -P cuda/lib64/libcudnn /usr/local/cuda/lib64
    $ sudo chmod a+r /usr/local/cuda/include/cudnn.h 
    /usr/local/cuda/lib64/libcudnn*

Now you should have tensorflow

Try it on typing in the console:

    $python
    import tensorflow

If you want to work in anaconda and the error persists , try :

    $jupyter notebook --generate-config

then you can find the name of the directory where you have your config file (Ill call it

) and open /jupyter_notebook_config.py and add at the top :

    import os
    c = get_config()
    os.environ['LD_LIBRARY_PATH'] = '/usr/local/cuda-8.0/lib64:usr/local/cuda-8.0/lib64/libcudart.so.8.0'
    c.Spawner.env.update('LD_LIBRARY_PATH')

Now it should work...

Here are the websites that helped me:

https://askubuntu.com/questions/952075/how-to-upgrade-tensorflow-to-v1-3-cudnn-cuda-upgrade
https://developer.nvidia.com/rdp/cudnn-download
https://medium.com/@ikekramer/installing-cuda-8-0-and-cudnn-5-1-on-ubuntu-16-04-6b9f284f6e77
https://stackoverflow.com/questions/43984135/tensorflow-gpu-can-not-be-called-from-jupyterhub-jupyter-notebook-why

**Comment by crmne** [comment]
If you don't mind using TensorFlow 1.4, you can simply run this in a jupyter notebook and restart the  python kernel:

    !pip install --user "tensorflow-gpu>=1.4,<1.5"

**Comment by jlewi** [comment]
There's an open issue to pin the version of TF in our notebook images and not use TF nightly #375

**Comment by jlewi** [comment]
#375 has been fixed. Our new Jupyter images should pin the version of TF and this should no longer be an issue.

**Comment by dharmeshkakadia** [comment]
@jlewi (anyone else who runs into this) This is an issue on Azure because of a different bug : https://github.com/kubeflow/kubeflow/issues/435
